repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - LICENSE
    - .github/CONTRIBUTING.md
    - .prettierignore
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-seminar_logo_light.png
    - docs/images/nf-core-seminar_logo_light.png
    - docs/images/nf-core-seminar_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  nf_test_content: false
  multiqc_config: false
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CHANGELOG.md
    - assets/multiqc_config.yml
    - LICENSE
    - .prettierignore
    - .prettierrc.yml
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/CONTRIBUTING.md
    - .github/.dockstore.yml
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CITATIONS.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-seminar_logo_light.png
    - docs/images/nf-core-seminar_logo_light.png
    - docs/images/nf-core-seminar_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
  readme:
    - nextflow_badge
    - nextflow_badge
    - nfcore_template_badge

template:
  org: nf-core
  name: seminar
  description: rna
  author: Amirabbas
  version: '1.0'
  force: true
  outdir: .
  skip_features:
    - github
    - github_badges
    - changelog
    - license
    - ci
    - nf-test
    - igenomes
    - multiqc
    - fastqc
    - seqera_platform
    - gpu
    - gitpod
    - codespaces
    - vscode
    - code_linters
    - citations
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
